### ISSUE TITLE
By Song vs By Album

### ISSUE THREAD

**Issue by johnjbarton** [pixfabrik/fathom#6]
Based on Pandora etc I was surprised that the whole album is queued. Now it's nice I have to say, but picking one song and moving on would give a different user experience, better for sampling a related set.  An option perhaps...

**Comment by iangilman** [comment]
We won't be doing as much playback with Spotify, so this may be moot. Beyond that, I'm still sold on Fathom being oriented around albums, as this is a big differentiator against the other entries in the market.
